#!/bin/sh
#
# A hook script to verify what is about to be committed.
# Called by "git commit --amend" or "git rebase". The hook exits with
# non-zero status and warning messages if the files being rewritten do
# not conform to to the Mesos style.
#
# To enable this hook, do this from the root of the repo:
#
# $ ln -s ../../support/hooks/post_rewrite .git/hooks/post_rewrite

# Redirect output to stderr.
exec 1>&2

# If there are whitespace errors, print the offending file names.
## In git, '@~' represent previous commit. We check the whitespace between
## current head and previous commit after a commit is rewritten.
git diff-index --check @~ -- || exit 1

# Check Mesos style.
## In git, '@' represent current head, '@~' represent previous commit. We check
## the style of changes between current head and previous commit after a commit
## is rewritten.
exec git diff --name-only --diff-filter=AM @~..@ | xargs ./support/mesos-style.py || exit 1

# Check that the commits are properly split between mesos, libprocess and stout.
## In git, '@' represent current head, '@~' represent previous commit. We check
## the style of changes between current head and previous commit after a commit
## is rewritten.
exec git diff --name-only --diff-filter=AMD @~..@ | xargs ./support/mesos_split.py || exit 1
