
sudo: required

services:
    - docker

env:
    global:
        - BUILDTOOL=autotools
        - COMPILER=gcc
        - CONFIGURATION='--enable-libevent --enable-ssl'
        - ENVIRONMENT='GLOG_v=1 MESOS_VERBOSE=1'
        - COMPILER_OPTS='-j2'
        - CXXFLAGS='-gsplit-dwarf'
        - AUTOTOOLS_TASK='all'
    matrix:
        - OS=ubuntu:14.04
        - OS=centos:7

script: support/docker_build.sh
