#!/bin/sh

# Note that we don't use '--no-recursive' becuase older versions of
# autoconf/autoreconf bail with that option. Unfortunately this means
# that we'll modify a lot of files in third_party/libprocess, but that
# may change in the future.

autoreconf --install -Wall --verbose "${@}"
