#!/bin/bash

SLAVES=/root/mesos-ec2/slaves
MASTER=/root/mesos-ec2/master
ZOO=/root/mesos-ec2/zoo

ISFT=`cat $ZOO | wc -l`

SSH_OPTS="-o StrictHostKeyChecking=no -o ConnectTimeout=2"

SERVERS=`cat $SLAVES`
SERVERS+=" "
SERVERS+=`cat $MASTER | sed '1d'`
SERVERS+=" "
SERVERS+=`cat $ZOO`


echo "RSYNC'ing /root/mesos to other servers..."
for server in $SERVERS; do
    echo $server
    rsync -e "ssh $SSH_OPTS" -az --exclude '*.d' --exclude '*.o' --exclude '*.cpp' --exclude '*.hpp' --exclude '*.pyc' --exclude 'mesos/frameworks/hadoop-0.20.0/logs/*' /root/mesos $server:/root &
done
wait

if [[ $ISFT != 0 ]] ; then
  echo "Configuring zoo.cfg..."
  for zoo in `cat $ZOO`; do
    zid=1
    for zoop in `cat $ZOO`; do
      ssh $SSH_OPTS $zoo echo "server."${zid}"="${zoop}":2888:3888" \>\> ~/mesos/src/third_party/zookeeper*/conf/zoo.cfg
      zid=$(($zid+1))
    done
    sleep 0.1
  done
fi
