source 'https://rubygems.org'

gem 'middleman', '~>3'
gem 'middleman-livereload', '~>3'
gem 'middleman-syntax', '~>3'
gem 'middleman-blog', '~>3'

# Middleman has an undeclared dependency on `tzinfo-data` for
# generating timestamps.
#
# TODO(bbannier): Remove this explicit dependency when middleman
# correctly declares its requirements.
gem 'tzinfo-data'

gem 'rdiscount', '2.2.0.1'

gem 'htmlentities'

gem 'therubyracer'

gem 'rake'
