source 'https://rubygems.org'

gem 'middleman', '3.2.0'
gem 'middleman-livereload', '3.1.0'
gem 'middleman-syntax', '1.2.1'
gem 'middleman-blog', '3.5.1'

gem 'rdiscount', '2.1.7'

gem 'htmlentities'

gem 'therubyracer'

gem 'rake'
