#! /usr/bin/env sh

apt-get -y install mpich2

touch /etc/mpi.conf
chmod 600 /etc/mpi.conf
echo "MPD_SECRETWORD=$PBS_JOBID" | cat >> /etc/mpi.conf

#setup up mpd daemon on this node
mpd --daemon
mpdtrace -l
#GET PORT NUMBERS HERE
PORTNUM=mpdtrace -l | cut -d"_" -f 2 | cut -d" " -f1
HOSTNAME= mpdtrace -l | cut -d"_" -f 2 | cut -d"(" -f2 | cut -d")" -f1

# set up mpi daemon on all slave nodes given to us by torque in $PBS_HOSTFILE
for i in cat `$PBS_HOSTFILE`; do ssh $i mpd --daemon -h $HOSTNAME -p $PORTNUM ; done

#then call the real mpiexec
echo mpiexec $@
