#!/bin/bash

SLAVES=/root/nexus-ec2/slaves
MASTER=/root/nexus-ec2/master
ZOO=/root/nexus-ec2/zoo

SSH_OPTS="-o StrictHostKeyChecking=no -o ConnectTimeout=2"

SERVERS=`cat $SLAVES`
SERVERS+=" "
SERVERS+=`cat $MASTER | sed '1d'`
SERVERS+=" "
SERVERS+=`cat $ZOO`


echo "RSYNC'ing /root/nexus to other servers..."
for server in $SERVERS; do
    echo $server
    rsync -e "ssh $SSH_OPTS" -az --exclude '*.d' --exclude '*.o' --exclude '*.cpp' --exclude '*.hpp' --exclude '*.pyc' --exclude 'nexus/frameworks/hadoop-0.20.0/logs/*' /root/nexus $server:/root &
done
wait