#!/bin/bash

cd /root/nexus-ec2

MASTER="`cat master`"
SLAVES="`cat slaves`"
ZOO="`cat zoo`"


SSH_OPTS="-o StrictHostKeyChecking=no -o ConnectTimeout=2"

for slave in $SLAVES; do
  echo "Killing ALL processes in ALL Nexus projects on $slave"
  ssh $SSH_OPTS $slave "for i in 0 1 2 3 4 5 6 7; do for pid in \$(pgrep -J nexus.project.\$i | grep -v \$(pgrep -J nexus.project.\$i projd)); do kill -9 \$pid; done; done"
done
