#!/bin/bash

cd /root/nexus-ec2

SLAVES_FILE="/root/nexus-ec2/slaves"
MASTER="`cat master`"
SLAVES="`cat $SLAVES_FILE`"

#These seem to be broken, i.e. missing directories after install
#ssh $MASTER "apt-get install -y torque-server"
#ssh $MASTER "apt-get install -y torque-scheduler"
#ssh $MASTER "apt-get install -y torque-client"

#install torque: download/unzip torque
function installmaster {
	pushd ~
	echo "downloading and installing torque on master"
	wget http://www.clusterresources.com/downloads/torque/torque-2.4.7.tar.gz
	tar xzf torque-2.4.7.tar.gz
	cd torque-2.4.7
	./configure --prefix=/usr/local
	make -j8
	make install
        ./torque.setup `whoami` #or should this just be root

	echo "copying init.d control scripts to master"
	cp contrib/init.d/debian.pbs_mom /nfs/torque/init.d/pbs_mom
	cp contrib/init.d/debian.pbs_sched /nfs/torque/init.d/pbs_sched
	cp contrib/init.d/debian.pbs_server /nfs/torque/init.d/pbs_server

	echo "running ldconfig on master"
	ldconfig
	popd
}

function installslaves {
	pushd ~/torque-2.4.7
	echo "building packages for slave"
	make packages
	#install torque-mom on slave nodes
	apt-get install -y dsh
	
        echo "copying slave install packages to nfs"
	mkdir /nfs/torque
	cp torque-package-mom-linux-x86_64.sh /nfs/torque/torque-package-mom-linux-x86_64.sh
	cp torque-package-mom-linux-x86_64.sh /nfs/torque/torque-package-clients-linux-x86_64.sh

	echo "installing torque mom and clients package on slaves"
	dsh -f $SLAVES_FILE /nfs/torque/torque-package-mom-linux-x86_64.sh --install
	dsh -f $SLAVES_FILE /nfs/torque/torque-package-clients-linux-x86_64.sh --install

	echo "copying pbs_mom init.d control script to slaves"
	mkdir /nfs/torque/init.d
	cp contrib/init.d/debian.pbs_mom /nfs/torque/init.d/debian.pbs_mom
	dsh -f $SLAVES_FILE cp /nfs/torque/init.d/debian.pbs_mom /etc/init.d/pbs_mom

	echo "Running ldconfig on slaves"
	dsh -f $SLAVES_FILE ldconfig
	popd
}

installmaster
installslaves
