#! /usr/bin/env sh

apt-get -y install dsh

dsh -f /root/nexus-ec2/slaves apt-get -y install mpich2


dsh -f /root/nexus-ec2/slaves rm /etc/mpd.conf
dsh -f /root/nexus-ec2/slaves touch /etc/mpd.conf
dsh -f /root/nexus-ec2/slaves "echo 'MPD_SECRETWORD=default' > /etc/mpd.conf"
dsh -f /root/nexus-ec2/slaves chmod 600 /etc/mpd.conf
echo "finished setting up /etc/mpd.conf with value MPD_SECRETWORD=default"
