#!/bin/bash
cd /root/nexus-ec2

MASTER="`cat master`"
SLAVES="`cat slaves`"
ZOO="`cat zoo`"

ISFT="`cat zoo | wc -l`"

SSH_OPTS="-o StrictHostKeyChecking=no -o ConnectTimeout=2"

for slave in $SLAVES; do
  echo "Stopping slave(s) on $slave"
  ssh $SSH_OPTS $slave pkill nexus-slave &
  sleep 0.1
done
wait

echo "Stopping master on $MASTER"
for master in $MASTER; do
  echo "Stopping master(s) on $master"
  ssh $SSH_OPTS $master pkill nexus-master &
  sleep 0.1
done
wait

if [[ $ISFT != 0 ]] ; then
  for zoo in $ZOO; do
    echo "Stopping ZK on $zoo"
    ssh $SSH_OPTS $zoo "/root/nexus/src/third_party/zookeeper-*/bin/zkServer.sh stop </dev/null >/dev/null"
    sleep 0.1
  done
  wait
fi
