#!/bin/bash
cd /root/nexus-ec2

MASTER="`cat master`"
SLAVES="`cat slaves`"

SSH_OPTS="-o StrictHostKeyChecking=no -o ConnectTimeout=2"

for slave in $SLAVES; do
  echo "Stopping slave(s) on $slave"
  ssh $SSH_OPTS $slave pkill nexus-slave &
  sleep 0.1
done
wait

echo "Stopping master on $MASTER"
ssh $SSH_OPTS $MASTER pkill nexus-master
