#!/bin/bash
FRAMEWORK_DIR="`cd $(dirname $0); pwd`"
MESOS_HOME="$FRAMEWORK_DIR/../../.."
export FRAMEWORK_DIR
exec java -cp $FRAMEWORK_DIR:$MESOS_HOME/lib/java/mesos.jar -Djava.library.path=$MESOS_HOME/lib/java TestFramework $@
