#!/usr/bin/env bash
#  Copyright 2015 Daniel Giribet <dani - calidos.cat>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[ -z "$JAVA_PACKAGES" ] && JAVA_PACKAGES='java-1.8.0-openjdk-headless java-1.8.0-openjdk-devel'

[ -z "$MAVEN_URL" ] && MAVEN_URL='https://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz'
[ -z "$PREFIX" ] && PREFIX='./.deps'

[ -z "$MAVEN_FILE" ] && MAVEN_FILE='apache-maven.tar.gz'
[ -z "$MAVEN_INSTALL_FOLDER_" ] && MAVEN_INSTALL_FOLDER_="$PREFIX/apache-maven"
[ -z "$M2_HOME" ] && M2_HOME="$MAVEN_INSTALL_FOLDER_"

# only use sudo when we are not root
SUDO_=
[ "$(id -u)" != "0" ] && export SUDO_=sudo

if [ -f /etc/redhat-release ]; then
	echo 'Installing dependencies with yum to build Mesos...'
	$SUDO_ yum install $JAVA_PACKAGES wget rpm-build -y -q
	# mesos-specific deps
	$SUDO_ yum groupinstall -y -q "Development Tools"
	$SUDO_ yum install -y -q python-devel zlib-devel libcurl-devel openssl-devel \
						   cyrus-sasl-devel cyrus-sasl-md5 apr-devel \
						   subversion-devel apr-util-devel python-boto
	$SUDO_ yum clean all
	
else
	echo 'Installing dependencies with apt-get to build Mesos...'
	$SUDO_ apt-get update
	$SUDO_ apt-get install -y -q --no-install-recommends rpm librpm-dev wget ca-certificates

	# java installation
	$SUDO_ sh -c "echo 'deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main' >> /etc/apt/sources.list"
	$SUDO_ sh -c "echo 'deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main' >> /etc/apt/sources.list"
	$SUDO_ apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C2518248EEA14886
	$SUDO_ apt-get update
	$SUDO_ sh -c "echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections"
	$SUDO_ apt-get install -y --no-install-recommends oracle-java8-installer \
		oracle-java8-set-default
	
	# mesos-specific deps
	$SUDO_ apt-get install -y -q --no-install-recommends build-essential python-dev \
		python-boto libcurl4-nss-dev libsasl2-dev libapr1-dev libsvn-dev \
		autoconf automake libtool libsasl2-modules 
	$SUDO_ apt-get clean
	
fi
echo 'Done installing Mesos dependencies'

# install maven on local folder if not installed
 mvn --version >/dev/null 2>&1
 if [ $? -ne 0 ]; then
 
 	if [ ! -e "$MAVEN_INSTALL_FOLDER_/bin/mvn" ]; then
	
		echo "Dowloading Maven at URL '$MAVEN_URL' ..."
		wget -q "$MAVEN_URL" -O "$MAVEN_FILE"
		if [ $? -ne 0 ]; then
			echo "Could not get Maven at URL '$MAVEN_URL' ($?)"
			exit 1
		fi
	
		echo "Extracting Maven into '$MAVEN_INSTALL_FOLDER_'"
		mkdir -p "$MAVEN_INSTALL_FOLDER_"
		tar xzf "$MAVEN_FILE" --strip=1 -C "$MAVEN_INSTALL_FOLDER_"
		rm -f "$MAVEN_FILE"
		echo 'Done'
		
	fi
 
 else
 	echo 'Maven already installed'
 fi
