#!/usr/bin/env bash
#  Copyright 2015 Daniel Giribet <dani - calidos.cat>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[ -z "$DOCKER" ] && DOCKER='docker'
[ -z "$IMAGE_NAME" ] && IMAGE_NAME='mesos-build-helper'
[ -z "$DOCKER_FILE" ] && DOCKER_FILE='Dockerfile'
[ -n "$MESOS_VER" ] && BUILD_ARGS="--build-arg mesos_ver=$MESOS_VER"

docker_build="$DOCKER build $BUILD_ARGS -t $IMAGE_NAME -f $DOCKER_FILE ."
echo "Executing the following docker build command: $docker_build"
eval $docker_build
if $(test $? -ne 0); then 
	echo "ERROR: compilation failed"
	exit 1
fi	       
sleep 5
echo 'Finding the Mesos rpm within the container...'
rpm_=$($DOCKER run "$IMAGE_NAME" find /build/target/rpm/mesos/RPMS -name '*.rpm')
name_=$(basename "$rpm_")
echo "Name of Mesos rpm: '$name_'"
echo 'Extracting the rpm...'
id_=$($DOCKER create "$IMAGE_NAME")
docker cp "$id_:$rpm_" .
docker rm -v "$id_"
echo 'Done, here you have your Mesos rpm:'
ls *.rpm
