#!/bin/sh
if [ "x$PYTHON" == "x" ]; then
  PYTHON=python
fi
FRAMEWORK_DIR="`cd $(dirname $0); pwd`"
export PYTHONPATH="$MESOS_HOME/lib/python:$MESOS_HOME/third_party/protobuf-2.3.0/python:$PYTHONPATH"
exec $PYTHON $FRAMEWORK_DIR/test_executor.py $@
