#!/bin/bash
if [ "x$PYTHON" == "x" ]; then
  PYTHON=python
fi
FRAMEWORK_DIR="`cd $(dirname $0); pwd`"
MESOS_HOME="$FRAMEWORK_DIR/../../.."
export PYTHONPATH="$MESOS_HOME/lib/python:$PYTHONPATH"
exec $PYTHON $FRAMEWORK_DIR/test_framework.py $@
