#! /usr/bin/env bash

DEPLOY_DIR=`dirname "$0"`
DEPLOY_DIR=`cd "$DEPLOY_DIR"; pwd`

. $DEPLOY_DIR/mesos-env.sh

echo "RSYNC'ing $MESOS_ROOT to slaves..."
for slave in $SLAVES; do
  echo $slave
  echo ssh $SSH_OPTS $slave "mkdir -p $MESOS_ROOT"
  ssh $SSH_OPTS $slave "mkdir -p $MESOS_ROOT"
  echo rsync -avz $MESOS_ROOT/ $slave:$MESOS_ROOT
  rsync -avz $MESOS_ROOT/ $slave:$MESOS_ROOT &
  sleep 0.1
done
