#!/usr/bin/env bash

DEPLOY_DIR=`dirname "$0"`
DEPLOY_DIR=`cd "$DEPLOY_DIR"; pwd`

. $DEPLOY_DIR/mesos-env.sh

ulimit -n 8192

PROGRAM=$1
shift

EXTRA_OPTS=""
if [ "$PROGRAM" == "mesos-slave" ]; then
  # Compute CPU and memory resources on this machine (TODO: Linux-specific)
  if [ `uname` == "Linux" ]; then
    CPUS=`grep processor /proc/cpuinfo | wc -l`
    MEM_KB=`cat /proc/meminfo | grep MemTotal | awk '{print $2}'`
    MEM=$[(MEM_KB - 1024 * 1024) / 1024] # Leaves 1 GB free
    EXTRA_OPTS="--resources=cpus:$CPUS;mem:$MEM"
  fi
fi


cd $DEPLOY_DIR
echo "now in dir `pwd`"
nohup $MESOS_SBIN/$PROGRAM "$EXTRA_OPTS" $@ </dev/null >/dev/null 2>&1 &
