#!/usr/bin/env bash
DEPLOY_DIR=`dirname "$0"`
DEPLOY_DIR=`cd "$DEPLOY_DIR"; pwd`

. $DEPLOY_DIR/mesos-env.sh

$DEPLOY_DIR/start-masters

sleep 1

$DEPLOY_DIR/start-slaves

echo "Everything's started! You should be able to view the master Web UI"

