#!/usr/bin/env bash
DEPLOY_DIR=`dirname "$0"`
DEPLOY_DIR=`cd "$DEPLOY_DIR"; pwd`
. $DEPLOY_DIR/mesos-env.sh

cd $DEPLOY_DIR

# Set OPTIONAL_SUDO_CMD to sudo if we should launch the slaves with sudo.
OPTIONAL_SUDO_CMD=""
if [ "$DEPLOY_WITH_SUDO" == "1" ]; then
  OPTIONAL_SUDO_CMD="sudo"
fi

# Launch slaves
for slave in $SLAVES; do
  echo "Starting slave on $slave"
  echo ssh $SSH_OPTS $slave "$OPTIONAL_SUDO_CMD $DEPLOY_DIR/mesos-daemon mesos-slave -m $MESOS_URL </dev/null >/dev/null" 
  ssh $SSH_OPTS $slave "$OPTIONAL_SUDO_CMD $DEPLOY_DIR/mesos-daemon mesos-slave -m $MESOS_URL </dev/null >/dev/null" &
  sleep 0.1
done
wait
