#!/usr/bin/env bash
DEPLOY_DIR=`dirname "$0"`
DEPLOY_DIR=`cd "$DEPLOY_DIR"; pwd`

. $DEPLOY_DIR/mesos-env.sh

cd $DEPLOY_DIR

#Launch master
echo "Starting master on $MASTER"
echo ssh $SSH_OPTS $MASTER "$DEPLOY_DIR/mesos-daemon mesos-master </dev/null >/dev/null"
ssh $SSH_OPTS $MASTER "$DEPLOY_DIR/mesos-daemon mesos-master </dev/null >/dev/null"
