#!/usr/bin/env bash
DEPLOY_DIR=`dirname "$0"`
DEPLOY_DIR=`cd "$DEPLOY_DIR"; pwd`

. $DEPLOY_DIR/mesos-env.sh

cd $DEPLOY_DIR

# Set OPTIONAL_SUDO_CMD to sudo if we launched the slave daemons with sudo,
# so that we can kill them as sudo.
OPTIONAL_SUDO_CMD=""
if [ "$DEPLOY_WITH_SUDO" == "1" ]; then
  OPTIONAL_SUDO_CMD="sudo"
fi

for slave in $SLAVES; do
  echo "Stopping slave on $slave"
  ssh $SSH_OPTS $slave "$OPTIONAL_SUDO_CMD killall mesos-slave" &
  sleep 0.1
done
wait
