#!/usr/bin/env bash
DEPLOY_DIR=`dirname "$0"`
DEPLOY_DIR=`cd "$DEPLOY_DIR"; pwd`

. $DEPLOY_DIR/mesos-env.sh

cd $DEPLOY_DIR

echo "Stopping master on $MASTER"
ssh $SSH_OPTS $MASTER "killall mesos-master"
