#!/usr/bin/env bash
DEPLOY_DIR=`dirname "$0"`
DEPLOY_DIR=`cd "$DEPLOY_DIR"; pwd`

. $DEPLOY_DIR/mesos-env.sh

cd $DEPLOY_DIR

# Set SUDO_COMMAND to sudo if we launched the slave daemons with sudo,
# so that we can kill them as sudo.
SUDO_COMMAND=""
if [ "$DEPLOY_WITH_SUDO" == "1" ]; then
  SUDO_COMMAND="sudo"
fi

for slave in $SLAVES; do
  echo "Stopping slave on $slave"
  ssh $SSH_OPTS $slave "$SUDO_COMMAND killall mesos-slave" &
  sleep 0.1
done
wait
