#!/usr/bin/env bash
DEPLOY_DIR=`dirname "$0"`
DEPLOY_DIR=`cd "$DEPLOY_DIR"; pwd`

. $DEPLOY_DIR/mesos-env.sh

cd $DEPLOY_DIR

for slave in $SLAVES; do
  echo "Stopping slave on $slave"
  ssh $SSH_OPTS $slave "killall mesos-slave" &
  sleep 0.1
done
wait
