#!/bin/bash

cd /root/nexus-ec2

MASTER="`cat master`"
SLAVES="`cat slaves`"

SSH_OPTS="-o StrictHostKeyChecking=no -o ConnectTimeout=2"

for slave in $SLAVES; do
  echo "Starting MapOutputServer on $slave"
  ssh $SSH_OPTS $slave "cd /root/nexus/frameworks/hadoop-0.20.0 ; ulimit -n 2048 ; export LD_PRELOAD_32=/usr/lib/extendedFILE.so.1 ; nohup ./bin/hadoop org.apache.hadoop.mapred.MapOutputServer > /tmp/MapOutputServer.log 2>&1 < /dev/null &" &
  sleep 0.1
done
wait
