#!/bin/bash

echo "Setting up Mesos slave on `hostname`..."

# Create Hadoop and HDFS directories in a given parent directory
# (for example /mnt, /mnt2, and so on)
function create_hadoop_dirs {
  location=$1
  mkdir -p $location/hdfs/dfs $location/hadoop/tmp $location/hadoop/mrlocal
}

# Set up Hadoop and Mesos directories in /mnt
create_hadoop_dirs /mnt
mkdir -p /mnt/hdfs-logs
mkdir -p /mnt/hadoop-logs
mkdir -p /mnt/mesos-logs
mkdir -p /mnt/mesos-work

# Mount any ephemeral volumes we might have beyond /mnt
function setup_extra_volume {
  device=$1
  mountpoint=$2
  if [ -e $device ]; then
    mkdir -p $mountpoint
    mount $device $mountpoint
    create_hadoop_dirs $mountpoint
  fi
}
setup_extra_volume /dev/sdc /mnt2
setup_extra_volume /dev/sdd /mnt3
setup_extra_volume /dev/sde /mnt4

# Mount cgroup file system
mkdir -p /cgroup
mount -t cgroup cgroup /cgroup
