#!/bin/bash

echo "Setting up Mesos slave on `hostname`..."

# Mount any ephemeral volumes we might have beyond /mnt
mkdir -p /mnt2 /mnt3 /mnt4
mount /dev/sdc /mnt2
mount /dev/sdd /mnt3
mount /dev/sde /mnt4
for i in /mnt /mnt2 /mnt3 /mnt4; do
  mkdir -p $i/hdfs/dfs $i/hadoop/tmp $i/hadoop/mrlocal
done
mkdir -p /mnt/hdfs-logs
mkdir -p /mnt/hadoop-logs
mkdir -p /mnt/mesos-logs
mkdir -p /mnt/mesos-work

# Mount cgroup file system
mkdir -p /cgroup
mount -t cgroup cgroup /cgroup
