#!/bin/bash
cd /root/mesos-ec2

MASTER="`cat master`"
SLAVES="`cat slaves`"

SSH_OPTS="-o StrictHostKeyChecking=no -o ConnectTimeout=2"

echo "Starting master on $MASTER"
ssh $SSH_OPTS $MASTER "/root/mesos-ec2/mesos-daemon mesos-master </dev/null >/dev/null"

for slave in $SLAVES; do
  echo "Starting slave on $slave"
  ssh $SSH_OPTS $slave "/root/mesos-ec2/mesos-daemon mesos-slave -u 1@$MASTER:5050 </dev/null >/dev/null" &
  sleep 0.1
done
wait

echo "Everything's started! You can view the master Web UI at"
echo "      http://$MASTER:8080"
